### ISSUE TITLE
Upcoming teleconference

### ISSUE THREAD

**Issue by gkellogg** [json-ld/yaml-ld#18]
I sent out a [Doodle](https://doodle.com/meeting/participate/id/e5yjL88e) to find a time for CG teleconference. Since the main activity of the group right now is YAML-LD, it would be good for people working on this to be involved. Historically, teleconferences are an important way to drive consensus and prioritize work, so even if you haven't been involved in the past, please consider attending at least the first such meeting. Calls are typically on Zoom, with meeting minutes recorded on the `#json-ld` IRC channel on irc.w3.org. See https://www.w3.org/2018/json-ld-wg/Meetings/#teleconferences.

Also, if you want to help in actively creating the UCR and Specifications, please request access, as noted in #1.

cc/ @VladimirAlexiev, @anatoly-scherbakov, @tetron, @nichtich, @ioggstream, @cmungall,

**Comment by VladimirAlexiev** [comment]
Thanks Gregg!

cc @HolgerKnublauch @ericprud @OR13 @nissimsan @msporny @vcharpenay @maximelefrancois86 @pchampin @giorgialodi @mr-c @tetron @danmoralesatx @sichvoge @krishahn

I hope I'm not spamming too widely, and I promise not to do it again. But this first telco is important because it's the kickoff of a YAML-LD working group (it's part of the JSON-LD CG, i.e. no commitment towards a formal recommendation).

Even if you cannot participate in the telco, please express your interest in working on YAML-LD (and/or Polyglot Modeling #19). Thanks!

**Comment by gkellogg** [comment]
The conference time has been settled for Jun 22, 2022 at 9:00 PDT, 12:00 EDT, 17:00 BST, 18:00 CEST. Details to follow.

**Comment by ioggstream** [comment]
@gkellogg call details? :)

**Comment by gkellogg** [comment]
Just sent out details: https://lists.w3.org/Archives/Public/public-linked-json/2022Jun/0001.html.

You can track upcoming activity on the [JSON-LD Calendar](https://www.w3.org/groups/cg/json-ld/calendar).
